import 'package:flutter/material.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedWidget14.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedMenubottonWidget1.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedScalesWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedLogo_uwk_21Widget1.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedMenuapWidget1.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedGroup62Widget1.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedGroup60Widget1.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/carappapp/generatedwidget12/generated/GeneratedVectorWidget14.dart';

/* Frame Поосевое взвещивание
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedMenuapWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 526.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedMenubottonWidget1(),
              ),
              Positioned(
                left: 11.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 362.9214172363281,
                height: 626.0,
                child: GeneratedWidget14(),
              ),
              Positioned(
                left: -5.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 36.0,
                child: GeneratedLogo_uwk_21Widget1(),
              ),
              Positioned(
                left: 283.0,
                top: 599.5800170898438,
                right: null,
                bottom: null,
                width: 34.0,
                height: 29.239980697631836,
                child: GeneratedGroup62Widget1(),
              ),
              Positioned(
                left: 2.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 33.0,
                child: GeneratedGroup60Widget1(),
              ),
              Positioned(
                left: 49.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedScalesWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08333333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.046875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.26944444444444443,
                        translateY: constraints.maxHeight * 0.0390625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget14())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
