import 'package:flutter/material.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedMenubottonWidget.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedTpaWidget2.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedWidget7.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedGroup60Widget.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedWidget4.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedMenuapWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedVectorWidget7.dart';
import 'package:flutterapp/carappapp/generatedwidget/generated/GeneratedLogo_uwk_21Widget.dart';

/* Frame Текущий вес
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedMenuapWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 526.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedMenubottonWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 36.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: -5.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 36.0,
                child: GeneratedLogo_uwk_21Widget(),
              ),
              Positioned(
                left: -3.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 105.0,
                child: GeneratedWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 132.0,
                right: 288.0,
                bottom: 483.0,
                width: null,
                height: null,
                child: GeneratedWidget7(),
              ),
              Positioned(
                left: 2.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 33.0,
                child: GeneratedGroup60Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 36.0,
                child: GeneratedTpaWidget2(),
              ),
              Positioned(
                left: 282.0,
                top: 599.5800170898438,
                right: null,
                bottom: null,
                width: 34.0,
                height: 29.239980697631836,
                child: GeneratedGroup62Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08333333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.046875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2722222222222222,
                        translateY: constraints.maxHeight * 0.0390625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget7())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
